Create meeting ical for AWS Working Group
ansible/community pull request #652
Opened 2022-03-16 16:52 UTC by alinabuzachis

Create meeting ical for AWS Working Group -  not sure if this is enough, I'll need some guidance otherwise.

2022-03-16 16:53 UTC, alinabuzachis commented
cc @tremble @markuman

2022-03-16 17:45 UTC, tremble requested changes

2022-03-16 17:45 UTC, tremble commented on meetings/aws.yaml
> +chair: Alina Buzachis (abuzachis), Mark Chappel (tremble), Markus Bergholz (markuman)
```suggestion
chair: Alina Buzachis (abuzachis), Mark Chappell (tremble), Markus Bergholz (markuman)
```

2022-03-16 17:48 UTC, alinabuzachis commented on meetings/ical/aws.ics
> + )\, Mark Chappel (tremble)\, Markus Bergholz (markuman)\nDescription:  \nW
Sorry for the type. Solved it.

2022-03-16 18:36 UTC, markuman approved these changes

2022-03-17 15:49 UTC, alinabuzachis commented
@cybette Can we merge this if it's sensible to you? Thanks.

2022-03-17 16:04 UTC, cybette commented on meetings/aws.yaml
> +  irc: ansible-aws or or https://matrix.to/#/#aws:ansible.im
one too many `or`s :)

2022-03-17 16:09 UTC, merged